name: SimplePerms
version: ${project.version}
main: de.asmax.simpleperms.Main
api-version: 1.16
authors: [ AsMax ]
description: A simple Plugin to manage Permissions
website: github.asmax.me

commands:
  spadd:
  spremove:
  sptemp:
  spget:
  spgadd:
  spgpadd:
  spgprem:
  spgdel:
  spglist:
  spgplist: